### ISSUE TITLE
Stack Scale parameters scales wrongly

### ISSUE THREAD

**Issue by unidesigner** [catsop/python-sopnet#8]
When extracting slices with ```SOPNET_STACK_SCALE = 0`` it appears they are scaled, twice as large in both x and y direction. It could be due to the recent changes introduced to deal with tile sources at different scale levels, e.g. in ```sopnet/catmaid/persistence/catmaid/CatmaidStackStore.cpp``.

The image tiles are retrieved with the correct URL encoding.

**Comment by aschampion** [comment]
I'm not able to reproduce this. With a fresh build of python-sopnet, truncated database, emptied component directory and the test stack slice component images and metadata rows both are the correct, unscaled size with `SOPNET_STACK_SCALE = 0`.

Are there specific steps/data you used when this error occurred?

**Comment by unidesigner** [comment]
Thanks, I'll into it again, its non-standard probability maps. I need to make sure that I truncate the database correctly, maybe I saw some outdated slices with a SOPNET_STACK_SCALE = 1 run - I guess this could explain it. The pysopnet code looked all correct to me.

**Comment by unidesigner** [comment]
False alarm. You were right, I was looking at an old run.
